WIP: feat(k6) - add k6 benchmarks
diegopacheco/servers-benchmark pull request #23
Opened 2023-10-03 16:54 UTC by LucasKonrath

### Explain the PR in a couple of words please

Language         [JS] <BR/>
Server/Framework [k6] <BR/>
Extra Notes: 
Adding k6 benchmarks for the servers in the project. 

Added a baseline test which receives url and test name through parameters, which will run a 1K-per-1-minute simulation (just like the gatling simulation), expose live metrics through http://127.0.0.1:5665 and after export an HTML file on the results folder.

Added scripts for each of the existing gatling simulations.

<BR/>

2023-10-08 06:29 UTC, diegopacheco requested changes
also make sure you have all simulations Gatling has:
```
ls *.sh | wc -l
59

```

2023-10-08 06:29 UTC, diegopacheco commented on k6-benchmarks/results/gleam-mist-1k.html
please remove this file @LucasKonrath  - no results on PRs pls.

2023-10-23 15:13 UTC, LucasKonrath commented on k6-benchmarks/results/gleam-mist-1k.html
done

2023-10-23 15:22 UTC, LucasKonrath commented
> also make sure you have all simulations Gatling has:
> 
> ```
> ls *.sh | wc -l
> 59
> ```

Done!

2023-10-23 23:26 UTC, diegopacheco approved these changes
Looks good.

2023-10-24 00:56 UTC, merged